apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: jump-app
  name: jump-app
spec:
  finalizers:
  - kubernetes

---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - jump-app
