apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-service-mesh-operators/application-argocd.yaml
- 01-service-mesh-control-plane/application-argocd.yaml
- 02-service-mesh-members-roll/02-service-mesh-members-roll.yaml
- 03-jump-app-deploy/03-jump-app-deploy.yaml
