apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 04-jump-app-deploy-blue-green
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 04-jump-app-deploy-blue-green
    repoURL: 'https://github.com/pkstaz/red-hat-service-mesh-demo.git'
    targetRevision: master
