apiVersion: v1
kind: Namespace
metadata:
  labels:
    kiali.io/member-of: istio-system
    kubernetes.io/metadata.name: istio-system
    maistra.io/member-of: istio-system
  name: istio-system
spec:
  finalizers:
  - kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-argocd-application-controller_edit_role"
  namespace: istio-system
roleRef:
  name: edit
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops

---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: istio-system
  name: basic
spec:
  security:
    identity:
      type: ThirdParty
      thirdParty:
        audience: istio-ca
  runtime:
    components:
      pilot:
        deployment:
          replicas: 1
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    enabled: true
    egress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
    ingress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
