apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: jump-app
  name: jump-app
spec:
  finalizers:
  - kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-argocd-application-controller_edit_role"
  namespace: jump-app
roleRef:
  name: edit
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops

---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - jump-app
