apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 02-service-mesh-members-roll
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 02-service-mesh-members-roll
    repoURL: 'https://github.com/pkstaz/red-hat-service-mesh-demo.git'
    targetRevision: master
