---
# Source: jump-app/charts/jump-app-micros/templates/istio/destinationrule.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: back-python
spec:
  host: back-python
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 3s
      baseEjectionTime: 10s
      maxEjectionPercent: 50
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: back-python
spec:
  gateways:
  - mesh
  hosts:
  - back-python
  http:
  - route:
      - destination:
          host: back-python.jump-app.svc.cluster.local
          subset: v1
        weight: 50
      - destination:
          host: back-python.jump-app.svc.cluster.local
          subset: v2
        weight: 50